### ISSUE TITLE
[Q] Compatibilty with open drivers and standards

### ISSUE THREAD

**Issue by mirh** [jloehr/KinectHeadTracking#1]
Namely 
https://github.com/opentrack/opentrack
https://github.com/OpenKinect/libfreenect2

**Comment by jloehr** [comment]
I did consider libfreenect2, but that is just a low level driver that makes available the raw images of the IR and RGB camera. It does not have any high level features like Skeleton tracking, High Definition Face tracking, etc.
For this project i need the eye position in 3D space and it seems there is no open-source implementation for that (though i just looked up libfreenect2).

That opentrack seems to be more like an application to convert from an abritary source to an arbitrary format/protocol for other applications. I didn't know about that. However it seems to not support the Kinect sensor and moreover i just needed an simple Lib/API to get the eye position.
